fix go formating in GH Actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,10 +40,16 @@ jobs:
       - name: Check Go formatting
         run: |
           go install golang.org/x/tools/cmd/goimports@v0.1.1
-          if [ $(goimports -l -local "github.com/G-Research/armada" | wc -l) -eq 0 ]; then exit 0; else exit 1; fi
+          if [ $? -ne 0 ]
+          then
+              echo "goimports installation failed" >&2
+              exit 1
+            fi
+          if [ $(goimports -d -local "github.com/G-Research/armada" . | wc -l) -eq 0 ]; then exit 0; else exit 1; fi
 
       - name: Run ineffassign
         run: |
+          cd /tmp
           go get -u github.com/gordonklaus/ineffassign
           cd ${{ env.GOPATH }}/src/github.com/G-Research/armada
           ineffassign ./...
